//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDAD_DOCTOR
    {
        public int id { get; set; }
        public int idEspecialidad { get; set; }
        public int idDoctor { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
    }
}
